---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trackpetsdb?serverTimezone=Europe/Madrid
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create  servlet:    multipart:      max-file-size: 10MB
      max-request-size: 10MB         mail:    host: smtp.gmail.com
    port: 465
    username: USERNAME@gmail.com
    password: PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp            
    test-connection: false      
logging:
  level: 
    org.hibernate.sql: debug

