---
spring:
  mvc:
    static-path-pattern: "/resources/**"
  datasource:
    url: jdbc:mysql://localhost:3306/trackpetsdb?serverTimezone=Europe/Madrid
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create  servlet:    multipart:      max-file-size: 10MB
      max-request-size: 10MB            
logging:
  level: 
    org.hibernate.sql: debug